POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Person test",
  "number": "523-2444"
}

###
PUT http://localhost:3001/api/persons/5fda483c5eb2c54de039b6c2
Content-Type: application/json

{
  "name": "t444 test",
  "number": "wolf cry"
}

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/5

###
GET http://localhost:3001/api/persons/5fd94615c368603f5014a355

###
DELETE http://localhost:3001/api/persons/5

###
DELETE http://localhost:3001/api/persons/5fd94615c368603f5014a355
