POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Person test",
  "number": "523-2444"
}

###
PUT http://localhost:3001/api/persons/5fda63ba1ef6c23080a45bf3
Content-Type: application/json

{
  "name": "t444444",
  "number": "355555555"
}

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/5

###
GET http://localhost:3001/api/persons/5fd94615c368603f5014a355

###
DELETE http://localhost:3001/api/persons/5

###
DELETE http://localhost:3001/api/persons/5fd94615c368603f5014a355
